---
extends: default

ignore-from-file: .gitignore

rules:
  comments:
    ignore: .github/workflows/build.yaml
  document-start:
    ignore: .github/workflows/build.yaml
  line-length:
    max: 120
    ignore: .github/workflows/build.yaml
  truthy:
    check-keys: false
