#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

FILE=$(date --iso-8601=minutes)-mysql-backup.sql.gz

# Dump database and compress
nice -n 19 mysqldump --compress --single-transaction femiwiki | nice -n 19 gzip -9 > "a/$FILE"

# Upload compressed file to AWS S3
aws s3 cp "a/$FILE" s3://femiwiki-backups
