#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

export LOCAL_SETTINGS="${LOCAL_SETTINGS:-/a/LocalSettings.php}"
if [ ! -z "$LOCAL_SETTINGS" ]; then
  DB_USERNAME="$(php -r 'require getenv("LOCAL_SETTINGS"); echo $wgDBuser;')"
  DB_PASSWORD="$(php -r 'require getenv("LOCAL_SETTINGS"); echo $wgDBpassword;')"
fi

echo "Use $DB_USERNAME user"

cat <<EOF >/root/.my.cnf
[mysqldump]
protocol=TCP
user=$DB_USERNAME
password=$DB_PASSWORD
single-transaction
EOF

touch /tmp/log
cron
tail -f /tmp/log
