#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

DB_SERVER="localhost"

export LOCAL_SETTINGS="${LOCAL_SETTINGS:-/a/LocalSettings.php}"
if [ ! -z "$LOCAL_SETTINGS" ]; then
  DB_SERVER="$(php -r 'require getenv("LOCAL_SETTINGS"); echo $wgDBserver;')"
  DB_USERNAME="$(php -r 'require getenv("LOCAL_SETTINGS"); echo $wgDBuser;')"
  DB_PASSWORD="$(php -r 'require getenv("LOCAL_SETTINGS"); echo $wgDBpassword;')"
fi

echo "Use $DB_USERNAME user"

cat <<EOF >/root/.my.cnf
[mysqldump]
protocol=TCP
host=$DB_SERVER
user=$DB_USERNAME
password=$DB_PASSWORD
single-transaction
EOF

FILE_NAME=$(date --iso-8601=minutes).sql.gz

# Dumps and compresses database, uploads backup file to AWS S3

for i in {1..5}; do
  echo "Trying to dump and compress... $i/5"
  nice -n 19 mysqldump --single-transaction femiwiki |
    nice -n 19 gzip -9 > $FILE_NAME &&\
    break || sleep 15
done

for i in {1..5}; do
  echo "Trying to upload... $i/5"
  nice -n 19 /usr/local/bin/aws s3 cp $FILE_NAME "s3://femiwiki-backups/mysql/${FILE_NAME}" &&\
    break || sleep 15
done
