#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

echo "Use $DB_USERNAME user"

cat <<EOF >/root/.my.cnf
[mysqldump]
protocol=TCP
host=$DB_SERVER
user=$DB_USERNAME
password=$DB_PASSWORD
single-transaction
EOF

touch /tmp/log
crond
tail -f /tmp/log
